btnfemcol/frontend/forms.py
from flaskext.wtf import *

from flaskext.wtf import PasswordField
from flaskext.wtf.html5 import *

from btnfemcol.admin.forms import UserEditForm

class UserFrontendForm(UserEditForm):
    password = PasswordField('Password',
        [optional(), equal_to('confirm_pass',
            message='Passwords must match.')])
    confirm_pass = PasswordField('Confirm Password')
    
class UserProfileForm(UserFrontendForm):
    username = None


class UserRegistrationForm(UserFrontendForm):
    password = PasswordField('Password',
        [Required(), equal_to('confirm_pass',
            message='Passwords must match.')])
    group_id = None
    status = None
    location = None
    website = None
    phone = None
    twitter = None

btnfemcol/frontend/__init__.py
from flask import Blueprint, g, session, config, current_app

from btnfemcol.models import User

frontend = Blueprint('frontend', __name__,
    template_folder='templates')

import views

btnfemcol/frontend/views.py
from datetime import datetime

from flask import g, redirect, url_for, abort, render_template, flash, \
    current_app

from btnfemcol.frontend import frontend

from btnfemcol import db, cache

from btnfemcol.models import Article, User, Page, Section, Category, Event

from btnfemcol.frontend.forms import UserRegistrationForm
from btnfemcol.frontend.utils import get, secondary_nav_pages, \
    secondary_nav_categories, q_events_upcoming

from btnfemcol.admin.utils import edit_instance, log_out, logged_in


@frontend.before_request
def before_request():
    key = 'sections'
    sections = cache.get(key)
    if not sections:
        sections = [{
            'url': s.url,
            'title': s.title,
            'slug': s.slug
        } for s in Section.get_live()]
        cache.set(key, sections, 20)
    g.sections = sections
    g.domain_name = current_app.config['DOMAIN_NAME']


# Blitz.io
@frontend.route('/mu-564346ee-4c8fbe62-92480e43-5112ec20')
def blitz():
    return '42'


@frontend.route('/events')
@frontend.route('/events/<string:type>')
@cache.memoize(20)
def show_events(type='upcoming'):
    def inner(type, limit=10):
        q = Event.query.filter_by(status='live')
        if type == 'upcoming':
            q = q_events_upcoming(q)
        else:
            q = q.order_by(Event.start.desc()).filter( \
                Event.start < datetime.utcnow())
        return q[:limit]

    return show_page('events', type, template='event_listing.html',
        events=inner(type))


@frontend.route('/event/<string:slug>')
@cache.memoize(20)
def show_event(slug):
    event = get(Event, slug)
    if not event:
        return abort(404)
    g.canonical_url = event.url
    g.secondary_nav = secondary_nav_pages('events')
    return render_template('event.html',
        page=event,
        selected_section_slug='events',
        selected_secondary_slug='changeme'
    )


@frontend.route('/articles')
@frontend.route('/articles/<string:category_slug>')
@cache.memoize(20)
def show_category(category_slug=None):
    if not category_slug:
        category = Category.query.filter_by(
            status='live').order_by(Category.order.asc()).first()
    else:
        category = get(Category, category_slug)
    if not category:
        return abort(404)

    articles = category.articles.filter_by(status='published').filter( \
                Article.pub_date <= datetime.utcnow()).order_by(
                    Article.pub_date.desc()).all()

    g.canonical_url = category.url
    g.secondary_nav = secondary_nav_categories()
    return render_template('category.html',
        category=category,
        articles=articles,
        selected_section_slug='articles',
        selected_secondary_slug=category_slug
    )


@frontend.route('/articles/<string:category_slug>/<string:article_slug>')
@cache.memoize(60)
def show_article(category_slug, article_slug):
    article = Article.query.filter(
            Article.pub_date <= datetime.now()
        ).filter_by(
            status='published', slug=article_slug
        ).first()
    if not article:
        return abort(404)

    g.secondary_nav = secondary_nav_categories()
    g.canonical_url = article.url
    return render_template('article.html',
        article=article,
        selected_section_slug='articles',
        selected_secondary_slug=category_slug
    )


def post_registration(id, saved, created, form):
    saved.send_activation_email()
    g.secondary_nav = secondary_nav_pages('home')
    return render_template('registered.html', user=saved)


@frontend.route('/register', methods=['GET', 'POST'])
def register():
    if logged_in():
        log_out()
    g.canonical_url = '/registration'
    g.secondary_nav = secondary_nav_pages('home')
    return edit_instance(User, UserRegistrationForm,
        edit_template='registration.html',
        callback=post_registration,
        do_flash=False)


@frontend.route('/activate/<int:user_id>/<string:reg_code>')
def activate(user_id, reg_code):
    user = User.query.filter_by(id=user_id).first()
    if not user:
        return abort(404)

    if user.reg_code != reg_code:
        return abort(403)

    if user.status == 'banned':
        return abort(403)

    user.status = 'active'

    try:
        db.session.commit()
    except Exception as e:
        current_app.logger.critical(e)
        db.session.rollback()

    flash('Your account has been activated.', 'success')
    return redirect(url_for('frontend.home'))


@frontend.route('/<string:slug>')
@cache.memoize(10)
def show_section(slug):
    section = get(Section, slug)
    if not section:
        return abort(404)
    page = section.pages.filter_by(status='live').first()
    if not page:
        return abort(404)
    else:
        page_slug = page.slug
    return show_page(slug, page_slug)


@frontend.route('/<string:section_slug>/<string:page_slug>')
@cache.memoize(10)
def show_page(section_slug, page_slug, template='page.html',
    **kwargs):

    page = get(Page, page_slug)

    if not page:
        return abort(404)

    g.secondary_nav = secondary_nav_pages(section_slug)
    g.canonical_url = page.url
    return render_template(template,
        page=page,
        selected_section_slug=section_slug,
        selected_secondary_slug=page_slug,
        **kwargs
    )


@frontend.route('/')
@cache.memoize(20)
def home():
    def articles():
        key = 'frontpage:articles'
        fp_arts = cache.get(key)
        if fp_arts:
            arts = []
            for art in fp_arts:
                arts.append(db.session.merge(art))
            fp_arts = arts
        if not fp_arts:
            fp_arts = Article.query.filter_by(
            status='published').filter(
            Article.pub_date <= datetime.now()).order_by(
            Article.pub_date.desc())[:2]
            cache.set(key, fp_arts, 30)
        return fp_arts

    def events():
        key = 'frontpage:events'
        fp_evts = cache.get(key)
        if not fp_evts:
            fp_evts = q_events_upcoming()[:2]
            cache.set(key, fp_evts, 30)
        return fp_evts

    first_section = get(Section)
    first_page = get(Page)
    return show_page(
        first_section.slug,
        first_page.slug,
        template='home.html',
        articles=articles(),
        events=events()
    )

btnfemcol/frontend/templates/article.html
{% extends 'page.html' %}
{% block title %}{{ article.title }} - Brighton Feminist Collective{% endblock %}
{% block meta_description %}{{ article.excerpt }}{% endblock %}
{% block meta_author %}{{ article.author.displayed_name }}{% endblock %}
{% block content %}
    {% block header %}
        <header class="ten columns article-header alpha omega offset-by-one">
            {{ article.tags_html }}
            <a href="{{ article.category.url }}" class="category">{{ article.category.title }}</a>
            <h1><span>{{ article.title }}</span></h1>
            <span class="subtitle">{{ article.subtitle }}</span>
            <span class="article display author">By {{ user_link(article.author) }}</span>
            <span class="date">{{ article.pub_date.strftime('%B %d, %Y') }}</span>
        </header>
    {% endblock %}
    {% block body %}
        <div class="ten columns offset-by-one alpha article-body">
            {{ article.body|markdown }}
        </div>
        <div id="disqus_thread"></div>
        <script type="text/javascript">
            /* * * CONFIGURATION VARIABLES: EDIT BEFORE PASTING INTO YOUR WEBPAGE * * */
            var disqus_shortname = 'brightonfeministcollective'; // required: replace example with your forum shortname
            var disqus_identifier = '{{ g.canonical_url }}';
            var disqus_url = 'http://www.brightonfeministcollective.org.uk{{ g.canonical_url }}';
            /* * * DON'T EDIT BELOW THIS LINE * * */
            (function() {
                var dsq = document.createElement('script'); dsq.type = 'text/javascript'; dsq.async = true;
                dsq.src = 'http://' + disqus_shortname + '.disqus.com/embed.js';
                (document.getElementsByTagName('head')[0] || document.getElementsByTagName('body')[0]).appendChild(dsq);
            })();
        </script>
        <noscript>Please enable JavaScript to view the <a href="http://disqus.com/?ref_noscript">comments powered by Disqus.</a></noscript>
        <a href="http://disqus.com" class="dsq-brlink">blog comments powered by <span class="logo-disqus">Disqus</span></a>
    {% endblock %}1
{% endblock %}

btnfemcol/frontend/templates/base.html
{% extends 'macros.html' %}
{%- macro user_link(user) -%}
<a href="{{ user.url }}">{{ user.displayed_name }}</a>
{%- endmacro -%}
{%- macro article_link(article) -%}
<a href="#">{{ article.title }}</a> by {{ user_link(article.author) }}
{%- endmacro -%}
{% block main %}<!doctype html>
<!--[if lt IE 7]> <html class="no-js lt-ie9 lt-ie8 lt-ie7" lang="en"> <![endif]-->
<!--[if IE 7]>    <html class="no-js lt-ie9 lt-ie8" lang="en"> <![endif]-->
<!--[if IE 8]>    <html class="no-js lt-ie9" lang="en"> <![endif]-->
<!--[if gt IE 8]><!--> <html class="no-js" lang="en"> <!--<![endif]-->
<head>
	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1"/>

	<title>{% block title %}Brighton Feminist Collective{% endblock %}</title>
	<meta name="description" content="{% block meta_description %}Started in December 2011, Brighton Feminist Collective is a sex-positive, pro-choice, trans-inclusive, and anti-exploitation feminist activist group.{% endblock %} " />
	<meta name="author" content="{% block meta_author %}Dapper Dog Studios{% endblock %}">
	<meta name="keywords" content="brighton, feminist, collective,  abort67, reclaim, dancefloor, abortion, feminism, activist, kyriarchy"/>

	<meta name="viewport" content="width=device-width" />
	<meta name="google-site-verification" content="w75DgnsnUjKK-QPT8wVABkSvoGYudGhpF12G5k0QaT4" />
	<meta name="google-site-verification" content="pca_v7HOtC5Xp0rnP5SMIr3tIO7r1UxqRT4SS3B-a8M" />
	<link href='http://fonts.googleapis.com/css?family=Poly:400,400italic' rel='stylesheet' type='text/css'>
	<link rel="stylesheet" href="{{ url_for('static', filename='css/base.css') }}">
	<link rel="stylesheet" href="{{ url_for('static', filename='css/skeleton.css') }}">
	<link rel="stylesheet" href="{{ url_for('static', filename='css/layout.css') }}">

	<link rel="canonical" href="http://www.brightonfeministcollective.org.uk{{ g.canonical_url }}" />
	{% block css %}{% endblock %}
	<script src="{{ url_for('static', filename='js/libs/modernizr-2.5.2.min.js') }}"></script>

	<script>
		var _gaq=[['_setAccount','UA-29822466-1'],['_trackPageview']];
		(function(d,t){var g=d.createElement(t),s=d.getElementsByTagName(t)[0];
		g.src=('https://ssl.google-analytics.com/ga.js');
		s.parentNode.insertBefore(g,s)}(document,'script'));
	</script>
	<script>
		window.domain_name = '{{ g.domain_name }}';
	</script>
</head>
<body>
<div id="main-container" class="container">
	<header class="main-header">
		<div class="sixteen columns">
			<h1><a href="/">Brighton Feminist Collective</a></h1>
		</div>
		<nav class="sixteen columns alpha omega">
			<ul class="primary">
				{% for section in g.sections %}
					<li class="
						{%- if section['slug'] == selected_section_slug: -%}
							selected
						{%- endif -%}"
					><a href="{{ section['url'] }}">{{ section['title'] }}</a>
				{% endfor %}
			</ul>
			<ul class="secondary">
				{% for item in g.secondary_nav %}
					<li class="
						{%- if item.slug == selected_secondary_slug: -%}
							selected
						{%- endif -%}"
					><a href="{{ item.url }}">{{ item.title }}</a></li>
				{% endfor %}
			</ul>
		</nav>
	</header>
	<section id="main" class="twelve columns main-column">
		{{ flashes() }}
		{% block content %}
		{% endblock %}
	</section>
	<aside class="columns four alpha omega" id="twitter">
	</aside>
	<footer class="columns sixteen alpha omega">
		Website by <a href="http://www.dapperdogstudios.com">Dapper Dog Studios</a>, Copyright &copy; 2012 Brighton Feminist Collective
	</footer>
</div>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.7.1/jquery.min.js"></script>
<script>window.jQuery || document.write('<script src="{{ url_for('static', filename='js/libs/jquery-1.7.1.min.js') }}"><\/script>')</script>

<script src="{{ url_for('static', filename='js/plugins.js') }}"></script>
<script src="{{ url_for('static', filename='js/tabs.js') }}"></script>
<script src="{{ url_for('static', filename='js/script.js') }}"></script>
{% block js %}{% endblock %}

</body>
</html>
{% endblock %}

btnfemcol/frontend/templates/category.html
{% extends 'page.html' %}
{% block content %}
        {% block header %}
        <header class="twelve columns alpha omega ">
            <h1>{{ category.title }}</h1>
        </header>
        {% endblock %}
        {% block posthead %}
        <div class="twelve columns alpha omega">
            {% if articles %}
                {% for article in articles %}
                    <article>
                        <header>
                            <h1><a href="{{ article.url }}">{{ article.title }}</a></h1>
                            <span class="date">{{ article.pub_date.strftime('%B %d, %Y') }}</span>
                        </header>
                        <p>{{ article.excerpt }}</p>
                    </article>
                {% endfor %}
            {% else %}
            <p>There are no articles in this category.</p>
            {% endif %}

        </div>
        {% endblock %}
{% endblock %}

btnfemcol/frontend/templates/event.html
{% extends 'page.html' %}
{% block title %}{{ page.title }} - Brighton Feminist Collective{% endblock %}
{% block meta_description %}{{ page.excerpt }}{% endblock %}
    {% block header %}
        <header class="twelve columns alpha omega">
            {{ page.tags_html|safe }}
            <h1>{{ page.title }}</h1>
            <span class="subtitle">Location: <a href="https://maps.google.co.uk/?q={{ page.location }}">{{ page.location }}</a></span>
            <span class="event date">Starts: {{ page.start.strftime('%B %d, %Y @ %H:%M') }}</span>
            <span class="event date">Ends: {{ page.end.strftime('%B %d, %Y @ %H:%M') }}</span>
        </header>
    {% endblock %}

btnfemcol/frontend/templates/event_listing.html
{% extends 'page.html' %}
{% block body %}
        <div class="twelve columns alpha omega">
            {{ page.body }}
            {% if events %}
                {% for event in events %}
                    <article>
                        <header>
                            <h1><a href="{{ event.url }}">{{ event.title }}</a></h1>
                            <span class="date">{{ event.start.strftime('%B %d, %Y @ %I:%M%p') }} &mdash; {{ event.start.strftime('%I:%M%p') }}</span>
                        </header>
                        <p>{{ event.excerpt }}</p>
                    </article>
                {% endfor %}
            {% else %}
            <p>There are no events to see.</p>
            {% endif %}

        </div>
{% endblock %}

btnfemcol/frontend/templates/home.html
{% extends 'page.html' %}
{% macro article_block(article, event=False) %}
    <article class="home listed">
        <a class="category" href="
        {%- if event: -%}
            {{ url_for('frontend.show_events')}}
        {%- else -%}
            {{ article.category.url }}
        {%- endif -%}">
            {% if event: %}
                Event
            {% else %}
                {{ article.category.title }}
            {% endif %}
        </a>
        <header>
            <h1 class=".tk-chinese-rocks"><a href="{{ article.url }}">{{ article.title }}</a></h1>
            {% if event: %}
                <span class="author">{{ article.start.strftime('%B %d, %Y @ %I:%M%p') }} &mdash; {{ article.end.strftime('%I:%M%p') }}</span>
            {% else %}
                <span class="author">by {{ article.author.displayed_name }}</span>
            {% endif %}
        </header>
        <p>{{ article.excerpt }}</p>
    </article>
{% endmacro %}
{% block header %}
    <div class="twelve columns alpha omega" id="black-bloc">
        <p class="six columns">Started in December 2011, Brighton Feminist Collective is a sex-positive, pro-choice, trans-inclusive, and anti-exploitation feminist activist group.</p>
        <p class="six columns">Follow <a href="http://twitter.com/BrightonFemCol">@BrightonFemCol</a> on Twitter</p>
        
        <p class="eight columns quote">&ldquo;My feminism will be intersectional or it will be bullshit!&rdquo; &ndash; Flavia Dzodan</p>
    </div>
    <div class="six columns alpha articles">
        {% for article in articles %}
            {{ article_block(article) }}
        {% endfor %}
    </div><div class="six columns omega events">
        

        {% for event in events %}
            {{ article_block(event, event=True) }}
        {% endfor %}
        
    </div>
    <hr />
{% endblock %}

btnfemcol/frontend/templates/page.html
{% extends 'base.html' %}
{% block content %}
        {% block prehead %}{% endblock %}
        {% block header %}
            <header class="twelve columns alpha omega ">
                <h1>{{ page.title }}</h1>
            </header>
        {% endblock %}
        {% block posthead %}{% endblock %}
        {% block body %}
            <div class="twelve columns alpha omega page">
                {{ page.body|markdown }}
            </div>
        {% endblock %}
        {% block postbody %}{% endblock %}
{% endblock %}

btnfemcol/frontend/templates/registered.html
{% extends 'base.html' %}
{% block content %}
    <header class="twelve columns alpha omega ">
        <h1>Nearly There...</h1>
    </header>

    <div class="twelve columns alpha omega">
        <p>You have successfully registered!</p>
        <p>An e-mail has been sent to <strong>{{ user.email }}</strong> with an activation link so you can 
            start using your account.</p>
        <p>Be sure to check spam folders because automated messages can sometimes become false-positives.</p>
    </div>
{% endblock %}

btnfemcol/frontend/templates/registration.html
{% extends 'base.html' %}
{% block content %}
    <header class="twelve columns alpha omega ">
        <h1>Registration</h1>
        <p>Registration will allow you initially to post comments. New writers are always welcome.</p>
        <p>Sign-up and e-mail <a href="mailto:brightonfeminists@gmail.com">brightonfeminists@gmail.com</a> if you'd like to submit articles!</p>
    </header>

    <div class="twelve columns alpha omega">
        <form method="POST">
            {% for field in form %}
                {{ render_field(field) }}
            {% endfor %}
            <input type="submit" value="{{ submit }}">
        </form>
    </div>
{% endblock %}